# -*- mode: ruby -*-
# vi: set ft=ruby :

#PLUGUINS

#unless Vagrant.has_plugin?("vagrant-vbguest")
  #puts 'Installing vagrant-vbguest Plugin...'
  #system('vagrant plugin install vagrant-vbguest')
#end

#unless Vagrant.has_plugin?("vagrant-hostmanager")
    #puts 'Installing vagrant-hostmanager Plugin...'
    #system('vagrant plugin install vagrant-hostmanager')
#end

#MACHINES

  Vagrant.configure(2) do |config|
    #config.hostmanager.enabled = true

    config.vm.box = "ubuntu/bionic64"
  
    config.vm.define "kafkutu", primary: true do |h|
      h.vm.hostname = "kafkutu"
      h.vm.network "private_network", ip: "192.168.1.120"
      #install kafka
      h.vm.provision :shell, path: "kafka_install_script.sh"
      h.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
      end
    end
  end
  
