# -*- mode: ruby -*-
# vi: set ft=ruby :

#PLUGUINS

#unless Vagrant.has_plugin?("vagrant-vbguest")
  #puts 'Installing vagrant-vbguest Plugin...'
  #system('vagrant plugin install vagrant-vbguest')
#end

unless Vagrant.has_plugin?("vagrant-hostmanager")
  puts 'Installing vagrant-hostmanager Plugin...'
  system('vagrant plugin install vagrant-hostmanager')
end

#MACHINES

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true

  config.vm.box = "centos/7"

  config.vm.define "centdockjens", primary: true do |h|
    h.vm.hostname = "centdockjens"
    #h.vm.network "public_network", ip: "192.168.1.100", bridge: "Intel(R) Wireless-AC 9560"
    #install docker from shell
    h.vm.provision :shell, path: "docker_install_script.sh"
    h.vm.provision :shell, path: "jenkins_install_script.sh"
    h.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end
end

